class GameScreens:
    START_SCREEN = "START_SCREEN"
    GAME_SCREEN = "GAME_SCREEN"
    GAME_OVER_SCREEN = "GAME_OVER_SCREEN"
    LEADER_BOARD_SCREEN = "LEADER_BOARD_SCREEN"
    QUIT_GAME = "QUIT_GAME"
